### PR TITLE
Don't keep JSObject * reference to coverage_statistics around.

### PR DESCRIPTION
**Pull request by smspillaz**
Keeping around pointers to JS objects on the C Heap is a recipe for
some pain, because if the GC runs and does a compaction, then
the pointer to its underlying data may become invalid.

The conservative stack scanner is supposed to catch this and prevent
that object from being GC'd, but it might not prevent its compartment
information from being moved.

The new approach is to wait until all scripts have finished
executing and then fetch the coverage_statistics object
instantiation from a property that we set on the
debugger_compartment and then store the result in a rooted
pointer. That way it will always be valid.

Fixes BGO #742466

### CODE REVIEW

**Comment by magcius** [comment]
> We were entering it as a compartment as well, which was completely
> wrong. Its parent object, debugger_compartment is the compartment.

`JSAutoCompartment` enters the compartment specified by the object you pass in. So it's a completely valid use.

**Comment by magcius** [comment]
> The conservative stack scanner
> is supposed to catch this and prevent that object from being GC'd,
> but it might not prevent it from being moved.

A generational GC, which is the case where the JS object will be moved, requires exact rooting. While we're making this change since SpiderMonkey 31 forces it upon us, this code should be fine. Have you seen issues with this in the wild?

**Comment by smspillaz** [comment]
@magicus: Yes, that was what was happening. The underlying `shape_` changes from underneath us and everything blows up later.

Whilst it is probably valid to enter the compartment of a non-root JSObject, the GC seems to be happy to move its data around when it does a compaction. It doesn't move around things that belong to root objects as far as I've observed.

**Comment by smspillaz** [comment]
Here's a [gist](gist.github.com/anonymous/2e86960c011bdd2e2be7) which doesn't reproduce the issue  yet (but might be of interest generally)

**Comment by smspillaz** [comment]
I had a chat to jdm on #jsapi about this. The internal `shape_->base_` ptr gets overwritten by `0xdadadada` which is apparently a canary for free'd memory. He suggested implementing a GC tracer hook to trace through to the object's compartment. He had to be somewhere, however, so I'm, not sure if his suggestion was supposed to be a workaround or an actual fix.

https://github.com/endlessm/gjs/tree/endlessm/fix_bgo742466_tracers implements such a tracer hook. This also seems to prevent the internals from being GC'd, which does what we want. If this is the right approach then we can drop this PR and continue on that branch instead.

**Comment by smspillaz** [comment]
jdm seems to agree. I'm closing this one and reopening on the newer branch

    00:41 < smspillaz> jdm: So implementing a global tracer on that object seemed to fix the problem
    00:42 < smspillaz> jdm: Should we stick with that? Or is there a potentially a cleaner way
    00:43 < jdm> I haven't thought of a better way yet. I'm surprised that PersistentRooted didn't exist, though.

**Pull request closed without merging**
