### PR TITLE
overrides: class property to set gtk css name

### PR DESCRIPTION
**Pull request by mattdangerw**
https://phabricator.endlessm.com/T11000

### CODE REVIEW

**Comment by mattdangerw** [comment]
Should probably get this one upstream as well

**Comment by ptomato** [comment]
Pretty trivial change and I think it's a good idea. Could you add a test to https://github.com/endlessm/gjs/blob/master/installed-tests/js/testGtk.js that checks the CSS name is set correctly with `Gtk.Widget.get_css_name()`? Also, is there an upstream issue for this?

**Comment by ptomato** [comment]
I just found out that almost this exact commit (though without the test) is on master already: https://github.com/GNOME/gjs/commit/c90238d969d6f4c96ea700921ad283cb92d1c53d

**Comment by mattdangerw** [comment]
@ptomato nice! That's funny.

If the test looks good to you, I can go ahead and push that to gjs master so we get it up there.

**Comment by ptomato** [comment]
I'm not a GJS reviewer, so maybe @cosimoc can OK it

**Comment by cosimoc** [comment]
@mattdangerw Your test looks good. Please do the following if you agree:
- commit the test to gjs master upstream
- in this PR, cherry-pick your upstream commit and the one @ptomato mentioned

**Comment by mattdangerw** [comment]
Done!

**Pull request merged**
